Update update-api.yml

diff --git a/.github/workflows/update-api.yml b/.github/workflows/update-api.yml
--- a/.github/workflows/update-api.yml
+++ b/.github/workflows/update-api.yml
@@ -2,18 +2,24 @@ name: Update API Data
 
 on:
   schedule:
-    - cron: '0 22 * * *'  # Spustí se každý den ve 22:00 UTC (půlnoc CEST)
-  workflow_dispatch:  # Umožní manuální spuštění
+    - cron: '0 22 * * *'
+  workflow_dispatch:
 
 jobs:
   update-data:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - name: Use Node.js
-      uses: actions/setup-node@v2
+      uses: actions/setup-node@v3
       with:
-        node-version: '14'
+        node-version: '20'
+    - name: List directory contents
+      run: ls -R
+    - name: Check file existence
+      run: |
+        [ -f src/generate-data.js ] && echo "generate-data.js exists" || echo "generate-data.js not found"
+        [ -f src/data/date.json ] && echo "date.json exists" || echo "date.json not found"
     - name: Generate API data
       run: node src/generate-data.js
     - name: Commit and push if changed
